### ISSUE TITLE
The example is not working?

### ISSUE THREAD

**Issue by HolyZheng** [wasm-tool/rollup-plugin-rust#27] opened 2021-12-16 01:53 UTC
1. clone this project
2. cd example
3. yarn install
4. yarn build

```js
yarn run v1.22.17
$ rimraf dist/js && rollup --config

Cargo.toml → dist/js...
```

just stuck in here

**Comment by Pauan** [comment] 2021-12-16 22:55
It works fine for me. What OS are you using? Are you able to build other Rust projects? Are you using a VPN?

**Comment by LeXXik** [comment] 2022-01-19 15:19
I get this output on example (Windows):

```
yarn run v1.22.10
$ rimraf dist/js && rollup --config

Cargo.toml → dist/js...
Error: spawnSync D:\dev\rapier\test\node_modules\@wasm-tool\rollup-plugin-rust\example\node_modules\binary-install\bin\wasm-pack.exe UNKNOWN
    at Object.spawnSync (internal/child_process.js:1067:20)
    at spawnSync (child_process.js:602:24)
    at Binary.run (D:\dev\rapier\test\node_modules\@wasm-tool\rollup-plugin-rust\example\node_modules\binary-install\index.js:84:20)
    at run (D:\dev\rapier\test\node_modules\@wasm-tool\rollup-plugin-rust\example\node_modules\wasm-pack\binary.js:34:10)
    at Object.<anonymous> (D:\dev\rapier\test\node_modules\@wasm-tool\rollup-plugin-rust\example\node_modules\wasm-pack\run.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawnSync D:\\dev\\rapier\\test\\node_modules\\@wasm-tool\\rollup-plugin-rust\\example\\node_modules\\binary-install\\bin\\wasm-pack.exe',  path: 'D:\\dev\\rapier\\test\\node_modules\\@wasm-tool\\rollup-plugin-rust\\example\\node_modules\\binary-install\\bin\\wasm-pack.exe',
  spawnargs: [
    '--log-level',
    'error',
    'build',
    '--out-dir',
    'D:\\dev\\rapier\\test\\node_modules\\@wasm-tool\\rollup-plugin-rust\\example\\target\\wasm-pack\\example',
    '--out-name',
    'index',
    '--target',
    'web',
    '--release',
    '--'
  ]
}
[!] (plugin rust) Error: Rust compilation failed
Cargo.toml
Error: Rust compilation failed
    at wasm_pack (D:\dev\rapier\test\node_modules\@wasm-tool\rollup-plugin-rust\example\node_modules\@wasm-tool\rollup-plugin-rust\index.js:171:19)   
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 0)
    at async build (D:\dev\rapier\test\node_modules\@wasm-tool\rollup-plugin-rust\example\node_modules\@wasm-tool\rollup-plugin-rust\index.js:353:22) 
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async Promise.all (index 0)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Pauan** [comment] 2022-01-19 16:05
Looks like some sort of regression in binary-install, I'll investigate this.

**Comment by Pauan** [comment] 2022-04-20 20:23
@LeXXik We were having a lot of issues with wasm-pack, so I removed wasm-pack in version 2.0.0. Please upgrade and let me know if you're still having the same issue.

If you're still having the same issue, please enable `verbose: true` and post your logs here.

**Comment by LeXXik** [comment] 2022-04-20 20:45
@Pauan thank you for looking into it! I will take a look at it this weekend, when I get to my code that used this.

**Comment by LeXXik** [comment] 2022-04-23 10:46
@Pauan it works now for me. I used Git Bash and PowerShell under Win11:

![image](https://user-images.githubusercontent.com/5677782/164891327-2c748b1e-516a-4ebd-8132-0315ff63f164.png)
![image](https://user-images.githubusercontent.com/5677782/164891338-cb3906f4-6670-4687-8608-82ee19766a38.png)

**Comment by Pauan** [comment] 2022-04-23 17:36
@LeXXik Thanks for letting me know. I'm going to close this now since it seems to be fixed.

**Closed as completed by Pauan** 2022-04-23 17:36 UTC
